// Unit tests for server/gcode-metadata.js: print time, filament grams, filament
// type, and printer model read from a sliced file's own header. Fixture lines
// use the exact formats each slicer writes (see the module's header comment for
// the sources); the PrusaSlicer values were also checked against real files
// from prusa3d/libbgcode's tests/data (mini_cube_ps2.8.1: 3m 41s, 0.75 g, PLA).

const zlib = require('zlib');
const { readPrintStats, parseDhms, readPrinterModelName, matchRegistryModel } = require('../gcode-metadata');
const { buildBgcode, buildZip } = require('./support/gcode-fixtures');

const PRUSA = [
  '; generated by PrusaSlicer 2.8.1+win64 on 2026-01-01 at 10:00:00 UTC',
  'G28',
  '; filament used [mm] = 252.22',
  '; filament used [g] = 0.75',
  '; estimated printing time (normal mode) = 1h 3m 41s',
  '; estimated printing time (silent mode) = 1h 5m 0s',
  '; prusaslicer_config = begin',
  '; filament_type = PLA',
  '; printer_model = MK4S',
  '; prusaslicer_config = end',
].join('\n');

describe('parseDhms', () => {
  test.each([['1d 2h 3m 4s', 93784], ['3m 41s', 221], ['41s', 41], ['2h 5m', 7500], ['', null], [null, null]])('%s', (s, n) => {
    expect(parseDhms(s)).toBe(n);
  });
});

describe('readPrintStats', () => {
  test('PrusaSlicer .gcode', () => {
    expect(readPrintStats('a.gcode', Buffer.from(PRUSA))).toEqual({ est_print_secs: 3821, material_grams: 0.75, material_type: 'PLA' });
  });

  test('PrusaSlicer .bgcode (metadata blocks, incl. zlib-compressed)', () => {
    const print = Buffer.from('filament used [g]=12.5\nestimated printing time (normal mode)=2h 0m 0s\n');
    const buf = buildBgcode([
      { type: 3, data: Buffer.from('printer_model=MK4S\nfilament_type=PETG\n') },
      { type: 4, compression: 1, data: print, compressedData: zlib.deflateSync(print) },
      { type: 1, data: Buffer.from('G28\n') },
    ]);
    expect(readPrintStats('a.bgcode', buf)).toEqual({ est_print_secs: 7200, material_grams: 12.5, material_type: 'PETG' });
    expect(readPrinterModelName('a.bgcode', buf)).toBe('MK4S');
  });

  test('OrcaSlicer, non-Bambu profile: normal-mode time and total grams win over the per-extruder list', () => {
    const orca = [
      '; HEADER_BLOCK_START', '; generated by OrcaSlicer 2.3.0 on 2026-01-01 at 10:00:00',
      '; estimated printing time (normal mode) = 2h 5m 0s', '; HEADER_BLOCK_END', 'G28',
      '; filament used [g] = 3.50, 1.25', '; total filament used [g] = 4.75', '; filament_type = PETG;PLA',
    ].join('\n');
    expect(readPrintStats('a.gcode', Buffer.from(orca))).toEqual({ est_print_secs: 7500, material_grams: 4.75, material_type: 'PETG, PLA' });
  });

  test('OrcaSlicer / Bambu Studio, Bambu profile: total estimated time and header weight', () => {
    const bbl = [
      '; HEADER_BLOCK_START', '; model printing time: 1h 2m 3s; total estimated time: 1h 10m 0s',
      '; total filament weight [g] : 12.34', '; HEADER_BLOCK_END', 'G28', '; filament_type = PLA;PLA',
    ].join('\n');
    expect(readPrintStats('a.gcode', Buffer.from(bbl))).toEqual({ est_print_secs: 4200, material_grams: 12.34, material_type: 'PLA' });
  });

  test('a sliced .3mf reads its plate G-code', () => {
    const zip = buildZip([{ name: 'Metadata/plate_1.gcode', data: Buffer.from(PRUSA), method: 8 }]);
    expect(readPrintStats('a.gcode.3mf', zip).est_print_secs).toBe(3821);
  });

  test('per-extruder grams are summed when there is no total', () => {
    const t = 'G28\n; filament used [g] = 3.50, 1.25\n';
    expect(readPrintStats('a.gcode', Buffer.from(t)).material_grams).toBe(4.75);
  });

  test('ideaMaker: seconds, and grams computed from length, diameter, density (kg/m3)', () => {
    const im = [
      ';Sliced by ideaMaker 4.4.1.6718, 2026', ';Filament Diameter #1: 1.75', ';Filament Density #1: 1240',
      ';Filament Type #1: PLA', 'G28', ';Print Time: 3725.4', ';Material#1 Used: 10000.0',
    ].join('\n');
    // pi/4 * 1.75^2 * 10000 * 1240 / 1e6 = 29.83 g
    expect(readPrintStats('a.gcode', Buffer.from(im))).toEqual({ est_print_secs: 3725, material_grams: 29.83, material_type: 'PLA' });
  });

  test('metadata only at the tail of a large file is still found', () => {
    const big = Buffer.concat([Buffer.from('; filament_type = ASA\n'), Buffer.alloc(3 * 1024 * 1024, 'G1 X1\n'), Buffer.from('\n; estimated printing time (normal mode) = 10h 0m 0s\n')]);
    expect(readPrintStats('a.gcode', big)).toMatchObject({ est_print_secs: 36000, material_type: 'ASA' });
  });

  test('a file with no metadata, or an unreadable one, gives nulls and never throws', () => {
    const none = { est_print_secs: null, material_grams: null, material_type: null };
    expect(readPrintStats('a.gcode', Buffer.from('G28\nG1 X1\n'))).toEqual(none);
    expect(readPrintStats('a.bgcode', Buffer.from('not bgcode'))).toEqual(none);
    expect(readPrintStats('a.3mf', Buffer.from('not a zip'))).toEqual(none);
  });
});

describe('matchRegistryModel', () => {
  const models = [
    { model_id: 'mk4', label: 'MK4' }, { model_id: 'mk4s', label: 'MK4S' },
    { model_id: 'c1', label: 'Core One' }, { model_id: 'x1c', label: 'X1 Carbon' },
  ];
  test.each([['MK4S', 'mk4s'], ['MK4', 'mk4'], ['COREONE', 'c1'], ['Bambu Lab X1 Carbon', 'x1c'], ['Ender-3', null], ['', null]])('%s -> %s', (s, id) => {
    expect(matchRegistryModel(s, models)).toBe(id);
  });
});
