// Tests for server/routes/slicer-upload.js: the OctoPrint- and Moonraker-
// compatible upload endpoint slicers post to (/slicer/<group>/...). Requests
// mirror what PrusaSlicer 2.9 (OctoPrint.cpp) and OrcaSlicer (OctoPrint.cpp,
// Moonraker.cpp) actually send.

const request  = require('supertest');
const express  = require('express');
const Database = require('better-sqlite3');
const path     = require('path');
const fs       = require('fs');
const auth     = require('../auth');
const { buildBgcode } = require('./support/gcode-fixtures');

const GCODE_DIR = path.join(__dirname, '..', 'gcode');
let db, app, key, uploaderKey, pendingKey;
const sweep = jest.fn();
const created = [];

beforeAll(() => {
  if (!fs.existsSync(GCODE_DIR)) fs.mkdirSync(GCODE_DIR, { recursive: true });
  db = new Database(':memory:');
  db.exec(`
    CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT, name TEXT, role TEXT, approved INTEGER DEFAULT 1,
      requires_print_approval INTEGER DEFAULT 0, password_hash TEXT, created_at INTEGER);
    CREATE TABLE api_keys (id INTEGER PRIMARY KEY, user_id INTEGER, name TEXT, key_prefix TEXT, key_hash TEXT,
      created_at INTEGER, last_used_at INTEGER, revoked_at INTEGER);
    CREATE TABLE printer_groups (name TEXT PRIMARY KEY, created_at INTEGER NOT NULL);
    CREATE TABLE printer_models (model_id TEXT PRIMARY KEY, label TEXT NOT NULL, connector TEXT NOT NULL);
    CREATE TABLE printers (id INTEGER PRIMARY KEY, name TEXT, model TEXT, group_name TEXT, is_active INTEGER DEFAULT 1);
    CREATE TABLE projects (id INTEGER PRIMARY KEY, name TEXT NOT NULL, description TEXT, status TEXT DEFAULT 'draft',
      priority INTEGER DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL,
      created_by_user_id INTEGER, created_by_name TEXT);
    CREATE TABLE parts (id INTEGER PRIMARY KEY, project_id INTEGER NOT NULL, name TEXT NOT NULL, target_qty INTEGER NOT NULL,
      completed_qty INTEGER DEFAULT 0, status TEXT DEFAULT 'open', sort_order INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, created_by_user_id INTEGER, created_by_name TEXT);
    CREATE TABLE gcodes (id INTEGER PRIMARY KEY, part_id INTEGER NOT NULL, printer_model TEXT NOT NULL, filename TEXT NOT NULL,
      filepath TEXT NOT NULL, parts_per_plate INTEGER NOT NULL, est_print_secs INTEGER, material_grams REAL,
      allowed_groups TEXT, approved INTEGER NOT NULL DEFAULT 1, uploaded_by_user_id INTEGER, uploaded_by_name TEXT,
      created_at INTEGER NOT NULL);
  `);
  const addUser = (id, name, role, extra = {}) => {
    db.prepare('INSERT INTO users (id, email, name, role, approved, requires_print_approval) VALUES (?, ?, ?, ?, ?, ?)')
      .run(id, `${name}@x`, name, role, extra.approved ?? 1, extra.rpa ?? 0);
    const k = auth.generateApiKey();
    db.prepare('INSERT INTO api_keys (user_id, name, key_prefix, key_hash, created_at) VALUES (?, ?, ?, ?, 1)').run(id, 'slicer', k.prefix, k.hash);
    return k.plaintext;
  };
  key = addUser(1, 'Alice', 'uploader');
  uploaderKey = addUser(2, 'Bob', 'uploader', { rpa: 1 });
  pendingKey = addUser(3, 'Pat', 'uploader', { approved: 0 });

  db.exec(`
    INSERT INTO printer_groups VALUES ('Rack A', 1), ('Mixed', 1), ('Empty', 1);
    INSERT INTO printer_models VALUES ('mk4s', 'MK4S', 'prusa'), ('mk4', 'MK4', 'prusa'), ('c1', 'Core One', 'prusa'), ('x1c', 'X1 Carbon', 'bambu');
    INSERT INTO printers (name, model, group_name) VALUES ('a1', 'mk4s', 'Rack A'), ('a2', 'mk4s', 'Rack A'),
      ('m1', 'mk4s', 'Mixed'), ('m2', 'c1', 'Mixed');
  `);

  app = express();
  app.use(express.json());
  app.use('/slicer', require('../routes/slicer-upload')(db, () => ({ sweepIdlePrinters: sweep })));
}, 30000);

afterAll(() => {
  for (const f of created) { try { fs.unlinkSync(path.join(GCODE_DIR, f)); } catch (_) {} }
});
beforeEach(() => sweep.mockClear());

function track(res) {
  if (res.body?.farm_gcode_id || res.body?.result?.farm_gcode_id) {
    const id = res.body.farm_gcode_id ?? res.body.result.farm_gcode_id;
    created.push(db.prepare('SELECT filepath FROM gcodes WHERE id = ?').get(id).filepath);
  }
  return res;
}

const gcode = (model) => Buffer.from(`; generated by PrusaSlicer\nG28\n${model ? `; printer_model = ${model}\n` : ''}`);

describe('connection tests', () => {
  test('OctoPrint GET /api/version passes PrusaSlicer\'s check (api present, text starts with OctoPrint)', async () => {
    const res = await request(app).get('/slicer/Rack%20A/api/version').set('X-Api-Key', key);
    expect(res.status).toBe(200);
    expect(res.body.api).toBeDefined();
    expect(res.body.text.startsWith('OctoPrint')).toBe(true);
  });

  test('Moonraker GET /server/info returns result.klippy_state', async () => {
    const res = await request(app).get('/slicer/Rack%20A/server/info').set('X-Api-Key', key);
    expect(res.body.result.klippy_state).toBe('ready');
  });

  test('missing or wrong API key is 401, unapproved account 403', async () => {
    expect((await request(app).get('/slicer/Rack%20A/api/version')).status).toBe(401);
    expect((await request(app).get('/slicer/Rack%20A/api/version').set('X-Api-Key', 'pfm_nope')).status).toBe(401);
    expect((await request(app).get('/slicer/Rack%20A/api/version').set('X-Api-Key', pendingKey)).status).toBe(403);
  });

  test('a Bearer API key also works', async () => {
    expect((await request(app).get('/slicer/Rack%20A/api/version').set('Authorization', `Bearer ${key}`)).status).toBe(200);
  });

  test('unknown group is 404', async () => {
    expect((await request(app).get('/slicer/Nope/api/version').set('X-Api-Key', key)).status).toBe(404);
  });
});

describe('OctoPrint upload (POST /api/files/local)', () => {
  test('queues the file as a part in the uploader\'s own project, restricted to the group', async () => {
    const res = track(await request(app).post('/slicer/Rack%20A/api/files/local').set('X-Api-Key', key)
      .field('print', 'true').field('path', '').attach('file', gcode('MK4S'), '4x Bracket.gcode'));
    expect(res.status).toBe(201);
    expect(res.body.files.local.name).toBe('4x Bracket.gcode');
    expect(res.body.done).toBe(true);

    const g = db.prepare('SELECT * FROM gcodes WHERE id = ?').get(res.body.farm_gcode_id);
    expect(g).toMatchObject({ printer_model: 'mk4s', parts_per_plate: 4, allowed_groups: '["Rack A"]', approved: 1, uploaded_by_name: 'Alice' });
    const part = db.prepare('SELECT * FROM parts WHERE id = ?').get(g.part_id);
    expect(part).toMatchObject({ name: '4x Bracket', target_qty: 4, created_by_name: 'Alice' });
    const project = db.prepare('SELECT * FROM projects WHERE id = ?').get(part.project_id);
    expect(project).toMatchObject({ name: 'Uploads: Alice', status: 'active', created_by_user_id: 1 });
    expect(sweep).toHaveBeenCalledTimes(1);
    expect(fs.existsSync(path.join(GCODE_DIR, g.filepath))).toBe(true);
  });

  test('a second upload reuses the same per-user project', async () => {
    const res = track(await request(app).post('/slicer/Rack%20A/api/files/local').set('X-Api-Key', key)
      .field('print', 'false').attach('file', gcode(null), 'Clip.gcode'));
    expect(res.status).toBe(201);
    expect(db.prepare("SELECT COUNT(*) AS n FROM projects WHERE name = 'Uploads: Alice'").get().n).toBe(1);
  });

  test('model falls back to the group\'s only model when the header has none', async () => {
    const res = track(await request(app).post('/slicer/Rack%20A/api/files/local').set('X-Api-Key', key)
      .attach('file', gcode(null), 'noheader.gcode'));
    expect(db.prepare('SELECT printer_model FROM gcodes WHERE id = ?').get(res.body.farm_gcode_id).printer_model).toBe('mk4s');
  });

  test('reads the model from a .bgcode header ("COREONE" matches "Core One")', async () => {
    const bg = buildBgcode([{ type: 3, data: Buffer.from('printer_model=COREONE\n') }, { type: 1, data: Buffer.from('G28\n') }]);
    const res = track(await request(app).post('/slicer/Mixed/api/files/local').set('X-Api-Key', key).attach('file', bg, 'part.bgcode'));
    expect(res.status).toBe(201);
    expect(db.prepare('SELECT printer_model FROM gcodes WHERE id = ?').get(res.body.farm_gcode_id).printer_model).toBe('c1');
  });

  test('ambiguous model in a mixed group is 400 and leaves nothing behind', async () => {
    const before = db.prepare('SELECT COUNT(*) AS n FROM gcodes').get().n;
    const files = fs.readdirSync(GCODE_DIR).length;
    const res = await request(app).post('/slicer/Mixed/api/files/local').set('X-Api-Key', key).attach('file', gcode(null), 'x.gcode');
    expect(res.status).toBe(400);
    expect(res.body.error).toMatch(/Could not tell which printer model/);
    expect(db.prepare('SELECT COUNT(*) AS n FROM gcodes').get().n).toBe(before);
    expect(fs.readdirSync(GCODE_DIR).length).toBe(files);
  });

  test('sliced for a model the group does not have is 400', async () => {
    const res = await request(app).post('/slicer/Rack%20A/api/files/local').set('X-Api-Key', key).attach('file', gcode('Bambu Lab X1 Carbon'), 'x.gcode');
    expect(res.status).toBe(400);
    expect(res.body.error).toMatch(/sliced for Bambu Lab X1 Carbon/);
  });

  test('"MK4S" header maps to mk4s, not mk4', async () => {
    const res = track(await request(app).post('/slicer/Mixed/api/files/local').set('X-Api-Key', key).attach('file', gcode('MK4S'), 'm.gcode'));
    expect(db.prepare('SELECT printer_model FROM gcodes WHERE id = ?').get(res.body.farm_gcode_id).printer_model).toBe('mk4s');
  });

  test('unsupported file type is 415', async () => {
    const res = await request(app).post('/slicer/Rack%20A/api/files/local').set('X-Api-Key', key).attach('file', Buffer.from('solid'), 'model.stl');
    expect(res.status).toBe(415);
  });

  test('a path-traversal filename is stored as a safe basename inside the gcode folder', async () => {
    const res = track(await request(app).post('/slicer/Rack%20A/api/files/local').set('X-Api-Key', key)
      .attach('file', gcode('MK4S'), '../../evil.gcode'));
    expect(res.status).toBe(201);
    const g = db.prepare('SELECT * FROM gcodes WHERE id = ?').get(res.body.farm_gcode_id);
    expect(g.filepath).not.toMatch(/[\\/]/);
    expect(g.filename).toBe('evil.gcode');
  });

  test('an account flagged requires_print_approval queues it unapproved and does not sweep', async () => {
    const res = track(await request(app).post('/slicer/Rack%20A/api/files/local').set('X-Api-Key', uploaderKey)
      .attach('file', gcode('MK4S'), 'b.gcode'));
    expect(db.prepare('SELECT approved FROM gcodes WHERE id = ?').get(res.body.farm_gcode_id).approved).toBe(0);
    expect(sweep).not.toHaveBeenCalled();
  });
});

describe('Moonraker upload (POST /server/files/upload)', () => {
  test('queues the file and answers with result.item.path', async () => {
    const res = track(await request(app).post('/slicer/Rack%20A/server/files/upload').set('X-Api-Key', key)
      .field('root', 'gcodes').field('plateindex', '1').attach('file', gcode('MK4S'), 'Orca part.gcode'));
    expect(res.status).toBe(201);
    expect(res.body.result.item).toEqual({ path: 'Orca part.gcode', root: 'gcodes' });
  });

  test('POST /printer/print/start is accepted (the upload already queued it)', async () => {
    const res = await request(app).post('/slicer/Rack%20A/printer/print/start').set('X-Api-Key', key).send({ filename: 'Orca part.gcode' });
    expect(res.status).toBe(200);
  });
});
